### ISSUE TITLE
Fix youtube URL

### ISSUE THREAD

**Issue by sudodaksh** [SaraVieira/graphiql-material-theme#1]
When, I queried your Home Page which is based on GraphQL, i found this talk:

```json
      {
        "name": "There's a whole new world offline",
        "event": "Require(\"lx\")",
        "date": "06/07/17",
        "video": "https://www.youtube.com/watch?v=ZvA41uuyujA&t=854s",
        "slides": "https://docs.google.com/presentation/d/1vQ9xAijI8NjbQkFESu0LwVYEcpCxqQhcjC7ESzddMTE/edit#slide=id.p",
        "done": true
      },
```

The youtube url there makes your talk start at 14 minutes, you can fix it by changing it to:

`https://www.youtube.com/watch?v=ZvA41uuyujA`

**Comment by SaraVieira** [comment]
Fixed in the latest version: http://iamsaravieira.com/

Thank you 🤗
